### ISSUE TITLE
amidakuji: make assets fails; unrecognized command line option ‘-mwindows’; did you mean ‘-m3dnow’?

### ISSUE THREAD

**Issue by mewmew** [faiface/pixel-examples#1]
Running on Arch Linux.

```
u@x1 ~/g/s/g/f/p/c/amidakuji> make
go-bindata -o "glossary/asset.go" -pkg "glossary" -prefix "assets" assets/emoji assets/karaoke assets/NanumBarunGothic.ttf
go build -i -v -o amidakuji -ldflags "-w -s -X main.version=d8311ef"
github.com/faiface/pixel-examples/community/amidakuji/glossary
github.com/faiface/pixel-examples/community/amidakuji/glossary/jukebox
github.com/faiface/pixel-examples/community/amidakuji
go build -i -v -o amidakuji.exe -ldflags "-w -s -X main.version=d8311ef -H windowsgui"
# github.com/faiface/pixel-examples/community/amidakuji
/home/u/go1.11/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
gcc: error: unrecognized command line option ‘-mwindows’; did you mean ‘-m3dnow’?

make: *** [Makefile:17: build_windows] Error 2
```

```
u@x1 ~> go version
go version devel +e03220a594 Sat Aug 25 02:39:49 2018 +0000 linux/amd64
```

**Comment by mewmew** [comment]
ping @NaniteFactory

**Comment by NaniteFactory** [comment]
Thanks for letting me know.

Logging error like that is an expected behavior. (It seems that your build was successful. Try running `./amidakuji`.)

`make` generates 2 separate binaries.
Former one targets (Linux or Windows or Mac), and the other is an .exe only for Windows.
Attempting to build the latter will fail on systems other than Windows.

But since it produces an error message I think people might find it misleading.
If so, Makefile can be edited to remove that part.

from this
`all: build build_windows`

to that
`all: build`

**Comment by mewmew** [comment]
Ah, I see. Thanks for the writeup. Yes, I could indeed run the `amidakuji` binary and it was fun to see you also had added background music :)

**Comment by faiface** [comment]
Is this issue still relevant?

**Comment by mewmew** [comment]
> Is this issue still relevant?

I think it can indeed be closed.
